---

#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

# Application settings
debug: true
port: 8080

# Database settings
database:
  host: localhost
  port: 3306
  name: app_db
  user: app_user
  password: p@ssw0rd

# Email settings
email:
  from: info@example.com
  host: smtp.example.com
  port: 587
  user: info@example.com
  password: p@ssw0rd
